theme = "black-and-light"
baseURL = "/opendays/"
title = "OpenTripPlanner OpenDays 2023"
author = "Steve Francia"
copyright = "Copyright © 2008–2019, Steve Francia and the Hugo Authors; all rights reserved."
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "./opendays/"
    weight = 1

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

