name: CI Build
on:
  push:
    branches:
      - main
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0

      - name: Install hugo and build site
        run: |
          sudo apt-get install hugo
          hugo